language: php

sudo: false

matrix:
  include:
    - php: 5.5.9
      env: LARAVEL_VERSION=5.1.*
    - php: 5.5.9
      env: LARAVEL_VERSION=5.2.*
    - php: 5.5
      env: LARAVEL_VERSION=5.1.*
    - php: 5.5
      env: LARAVEL_VERSION=5.2.*
    - php: 5.6
      env: LARAVEL_VERSION=5.1.*
    - php: 5.6
      env: LARAVEL_VERSION=5.2.*
    - php: 5.6
      env: LARAVEL_VERSION=5.3.*
    - php: 5.6
      env: LARAVEL_VERSION=5.4.*
    - php: 7.0
      env: LARAVEL_VERSION=5.1.*
    - php: 7.0
      env: LARAVEL_VERSION=5.2.*
    - php: 7.0
      env: LARAVEL_VERSION=5.3.*
    - php: 7.0
      env: LARAVEL_VERSION=5.4.*
    - php: 7.0
      env: LARAVEL_VERSION=5.5.*
    - php: 7.1
      env: LARAVEL_VERSION=5.1.*
    - php: 7.1
      env: LARAVEL_VERSION=5.2.*
    - php: 7.1
      env: LARAVEL_VERSION=5.3.*
    - php: 7.1
      env: LARAVEL_VERSION=5.4.*
    - php: 7.1
      env: LARAVEL_VERSION=5.5.*
    - php: 7.1
      env: LARAVEL_VERSION=5.6.*
    - php: 7.2
      env: LARAVEL_VERSION=5.1.*
    - php: 7.2
      env: LARAVEL_VERSION=5.2.*
    - php: 7.2
      env: LARAVEL_VERSION=5.3.*
    - php: 7.2
      env: LARAVEL_VERSION=5.4.*
    - php: 7.2
      env: LARAVEL_VERSION=5.5.*
    - php: 7.2
      env: LARAVEL_VERSION=5.6.*
      dist: trusty

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi
  - composer self-update --stable -n
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script: vendor/bin/phpunit
